
EQUIP_MAP = {
    "Gun Rammer": "rammer",
    "Improved Ventilation": "improvedVentilation",
    "Vertical Stabilizer": "aimingStabilizer",
    "Turbocharger": "turbocharger",
    "Improved Hardening": "extraHealthReserve",
    "Low-Noise Exhaust System": "additionalInvisibilityDevice",
    "Coated Optics": "coatedOptics",
    "Commander's Vision System": "commandersView",
    "Binocular Telescope": "stereoscope",
    "Camouflage Net": "camouflageNet",
    "Spall Liner": "antifragmentationLining",
    "Modified Configuration": "improvedConfiguration",
    "Improved Rotation Mechanisms": "improvedRotationMechanism",
    "Enhanced Gun Laying Drives": "enhancedAimDrives",
    "Improved Aiming": "improvedSights",
    "Experimental Turbocharger": "modernizedTurbochargerRotationMechanism",
    "Experimental Hardening": "extraHealthReserve",
    "Experimental Optics": "modernizedImprovedSightsEnhancedAimDrives",
    "healthReserve": "extraHealthReserve",
    "Experimental Gun Laying": "improvedSights",
    "Innovative Loading System": "improvedSights",
    "Additional Grousers": "grousers",
    "Extra Health Reserve": "extraHealthReserve",
    "additInvisibilityDevice": "additionalInvisibilityDevice",
    "rotationMechanism": "improvedRotationMechanism",
    "Enhanced Gun Laying Drive": "enhancedAimDrives",
    "Improved Rotation Mechanism": "improvedRotationMechanism",
    "Low Noise Exhaust System": "additionalInvisibilityDevice",
    "Superheavy Spall Liner": "antifragmentationLining",
    "Stabilizing Equipment System": "aimingStabilizer",
    "Wear-Resistant Gun Laying Drive": "enhancedAimDrives",
    "Improved Configuration": "improvedConfiguration",
    "Venting System": "improvedVentilation",
    "Improved Compressor": "turbocharger",
    "Increased Shell Resistance": "extraHealthReserve",
    "Improved Final Drive": "improvedRotationMechanism",
    "Innovative Targeting": "improvedSights",
    "Stealth Exhaust Unit": "additionalInvisibilityDevice",
    "Telescopic Observation System": "stereoscope",
    "Tactical Concealment Net": "camouflageNet",
}

CONS_MAP = {
    "Small Repair Kit": "smallRepairkit",
    "Large Repair Kit": "largeRepairkit",
    "Small First Aid Kit": "smallMedkit",
    "Large First Aid Kit": "largeMedkit",
    "Manual Fire Extinguisher": "handExtinguishers",
    "Automatic Fire Extinguisher": "autoExtinguishers",
    "Removed Speed Governor": "removedRpmLimiter",
    "100-octane Gasoline": "qualityFuel",
    "105-octane Gasoline": "excellentFuel",
    "Extra Rations (USSR)": "ration",
    "Extra Rations": "ration",
    "Case of Cola (USA)": "cocacola",
    "Cola": "cocacola",
    "Chocolate (Germany)": "chocolate",
    "Chocolate": "chocolate",
    "Pudding and Tea (UK)": "ration_uk",
    "Pudding and Tea": "ration_uk",
    "Strong Coffee (France)": "hotCoffee",
    "Improved Rations (China)": "ration_china",
    "Improved Combat Rations": "ration_china",
    "Bread with Lard (Poland)": "ration_poland",
    "Bread with Smalec": "ration_poland",
    "Buchty (Czechoslovakia)": "ration_czech",
    "Buchty": "ration_czech",
    "Spaghetti with Meat Sauce (Italy)": "ration_italy",
    "Onigiri (Japan)": "ration_japan",
    "Onigiri": "ration_japan",
    "Coffee with Cinnamon (Sweden)": "ration_sweden",
    "Coffee with Cinnamon Buns": "ration_sweden",
}

CREW_SKILL_MAP = {
    "Brothers in Arms": "brotherhood",
    "Repair": "repair",
    "Repairs": "repair",
    "Concealment": "camouflage",
    "Firefighting": "fireFighting",
    "Recon": "commander_eagleEye",
    "Eagle Eye": "commander_eagleEye",
    "Emergency": "commander_emergency",
    "Mentor": "commander_tutor",
    "Coordination": "commander_coordination",
    "Sound Detection": "commander_enemyShotPredictor",
    "Enemy Shot Predictor": "commander_enemyShotPredictor",
    "Practicality": "commander_practical",
    "Hold the Line": "commander_holdLine",
    "Stay Sharp": "commander_staySharp",
    "Snap Shot": "gunner_smoothTurret",
    "Smooth Turret": "gunner_smoothTurret",
    "Deadeye": "gunner_rancorous",
    "Dead Eye": "gunner_rancorous",
    "Rancorous": "gunner_rancorous",
    "Designated Target": "gunner_sniper",
    "Armorer": "gunner_armorer",
    "Steady Aim": "gunner_focus",
    "Quick Aiming": "gunner_quickAiming",
    "Point Blank": "gunner_pointBlast",
    "Lone Wolf": "gunner_loneWolf",
    "Smooth Ride": "driver_smoothDriving",
    "Smooth Driving": "driver_smoothDriving",
    "Off-Road Driving": "driver_badRoadsKing",
    "Clutch Braking": "driver_virtuoso",
    "Virtuoso": "driver_virtuoso",
    "Controlled Impact": "driver_rammingMaster",
    "Ramming Master": "driver_rammingMaster",
    "Reliable Placement": "driver_reliablePlacement",
    "Engineer": "driver_motorExpert",
    "Field Support": "driver_suspensionRepair",
    "Bulletproof": "driver_bulletproof",
    "Adrenaline Rush": "loader_desperado",
    "Desperado": "loader_desperado",
    "Safe Stowage": "loader_pedant",
    "Intuition": "loader_intuition",
    "Perfect Charge": "loader_perfectCharge",
    "Close Combat": "loader_melee",
    "Ammo Tuning": "loader_ammunitionImprove",
    "The Second Chance": "loader_secondChance",
    "Mag Mastery": "loader_magMastery",
    "Situational Awareness": "radioman_finder",
    "Relayer": "radioman_finder",
    "Signal Interception": "radioman_signalInterception",
    "Jamming": "radioman_interference",
    "Communications Expert": "radioman_expert",
    "Side by Side": "radioman_sideBySide",
    "Threat Search": "radioman_threatSearch",
    "Battle Tempered": "radioman_battleTempered",
    "Sixth Sense": "commander_sixthSense",
}
